create table Company_LCIAA (
	id INT,
	company_name VARCHAR(50),
	Address_1 VARCHAR(50),
	address_2 VARCHAR(50),
	City VARCHAR(50),
	State VARCHAR(6),
	Zip_Code VARCHAR(50),
	Phone_Number VARCHAR(50),
	SIC_Code VARCHAR(50),
	Social_Media_Link VARCHAR(50),
	Status VARCHAR(11),
	Company_Webpage VARCHAR(50)
);
insert into Company_LCIAA (id, company_name, Address_1, address_2, City, State, Zip_Code, Phone_Number, SIC_Code, Social_Media_Link, Status, Company_Webpage) values (1, 'Shufflester', '59 Columbus Crossing', 'Suite 79', 'Wangkung', 'Tex.', null, '291-966-3905', '751', 'https://4+.CCp', 'Pending', 'qwznysql\.com');
insert into Company_LCIAA (id, company_name, Address_1, address_2, City, State, Zip_Code, Phone_Number, SIC_Code, Social_Media_Link, Status, Company_Webpage) values (2, 'Tazzy', '0 Little Fleur Circle', '18th Floor', 'Colos', 'Ore.', '7630-305', '193-194-9618', '312', 'https://w+.yrY', 'Pending', 'vcmmucshcl\.com');
insert into Company_LCIAA (id, company_name, Address_1, address_2, City, State, Zip_Code, Phone_Number, SIC_Code, Social_Media_Link, Status, Company_Webpage) values (3, 'Demivee', '3071 Hanson Street', 'Room 1204', 'Kusak', 'N.Y.', '423430', '140-579-8687', '375', 'https://4+.VFg/S*', 'Pending', 'http://ahszxcdquf\.com');
insert into Company_LCIAA (id, company_name, Address_1, address_2, City, State, Zip_Code, Phone_Number, SIC_Code, Social_Media_Link, Status, Company_Webpage) values (4, 'Zoombeat', '920 Fuller Place', 'PO Box 64584', 'Nürnberg', 'Ore.', '90451', '732-644-2777', '854', 'http://3+.HVY/S*', 'Pending', 'www\.seaqzkce\.net');
insert into Company_LCIAA (id, company_name, Address_1, address_2, City, State, Zip_Code, Phone_Number, SIC_Code, Social_Media_Link, Status, Company_Webpage) values (5, 'Vimbo', '6001 Petterle Pass', '19th Floor', 'Krajan', 'Conn.', null, '752-909-1776', '790', 'https://V+.uY/S*', 'Pending', 'wwdrdf\.net');
insert into Company_LCIAA (id, company_name, Address_1, address_2, City, State, Zip_Code, Phone_Number, SIC_Code, Social_Media_Link, Status, Company_Webpage) values (6, 'Jaxnation', '0 School Hill', 'Suite 58', 'Mariental', 'Ariz.', null, '158-382-9186', '106', 'http://3+.Piy/S*', 'Pending', 'http://www\.xaolhns\.org');
insert into Company_LCIAA (id, company_name, Address_1, address_2, City, State, Zip_Code, Phone_Number, SIC_Code, Social_Media_Link, Status, Company_Webpage) values (7, 'Twinte', '6 Welch Terrace', 'Suite 63', 'Gowurdak', 'Ore.', null, '552-700-5449', '326', 'https://n+.Ng', 'Pending', 'http://iemnmkyjjv\.org');
insert into Company_LCIAA (id, company_name, Address_1, address_2, City, State, Zip_Code, Phone_Number, SIC_Code, Social_Media_Link, Status, Company_Webpage) values (8, 'Topiclounge', '281 Sloan Road', 'Apt 1449', 'Timezgana', 'D.C.', null, '970-713-9873', '268', 'https://s+.fOr/S*', 'Pending', 'http://www\.kpqrbdo\.org');
insert into Company_LCIAA (id, company_name, Address_1, address_2, City, State, Zip_Code, Phone_Number, SIC_Code, Social_Media_Link, Status, Company_Webpage) values (9, 'Ainyx', '01495 Briar Crest Terrace', 'Apt 1802', 'Ōmihachiman', 'Wash.', '527-0087', '489-340-9126', '347', 'http://I+.fb/S*', 'In Progress', 'wknwdbnp\.net');
insert into Company_LCIAA (id, company_name, Address_1, address_2, City, State, Zip_Code, Phone_Number, SIC_Code, Social_Media_Link, Status, Company_Webpage) values (10, 'Topicshots', '6 Pierstorff Plaza', 'PO Box 30333', 'San Martin', 'W.Va.', '9002', '381-544-9436', '63', 'http://v+.ZlG', 'Pending', 'wcsyks\.net');
insert into Company_LCIAA (id, company_name, Address_1, address_2, City, State, Zip_Code, Phone_Number, SIC_Code, Social_Media_Link, Status, Company_Webpage) values (11, 'Skibox', '1 Vahlen Point', 'Room 1385', 'Hetang', 'Idaho', null, '754-141-5506', '849', 'http://K+.wr', 'In Progress', 'www\.wxpbo\.net');
insert into Company_LCIAA (id, company_name, Address_1, address_2, City, State, Zip_Code, Phone_Number, SIC_Code, Social_Media_Link, Status, Company_Webpage) values (12, 'Zava', '2379 Drewry Road', 'Suite 64', 'Caocun', 'N.J.', null, '534-411-2321', '133', 'http://2+.Tv/S*', 'In Progress', 'pwxwq\.com');
insert into Company_LCIAA (id, company_name, Address_1, address_2, City, State, Zip_Code, Phone_Number, SIC_Code, Social_Media_Link, Status, Company_Webpage) values (13, 'Thoughtbridge', '051 Lawn Circle', 'Room 244', 'Al Jamīmah', 'Miss.', null, '237-598-1340', '558', 'https://5+.Vf/S*', 'Pending', 'jikjzo\.com');
insert into Company_LCIAA (id, company_name, Address_1, address_2, City, State, Zip_Code, Phone_Number, SIC_Code, Social_Media_Link, Status, Company_Webpage) values (14, 'Twinder', '0976 Ridgeway Street', 'PO Box 29146', 'Tianhe', 'Fla.', null, '685-750-5312', '172', 'http://P+.oDm/S*', 'Pending', 'http://www\.ehercfikid\.net');
insert into Company_LCIAA (id, company_name, Address_1, address_2, City, State, Zip_Code, Phone_Number, SIC_Code, Social_Media_Link, Status, Company_Webpage) values (15, 'Thoughtmix', '453 Kingsford Center', '6th Floor', 'Abbeville', 'Wis.', '80146 CEDEX', '922-843-1322', '104', 'https://G+.Hn/S*', 'Pending', 'www\.seyanpics\.com');
insert into Company_LCIAA (id, company_name, Address_1, address_2, City, State, Zip_Code, Phone_Number, SIC_Code, Social_Media_Link, Status, Company_Webpage) values (16, 'Brainlounge', '828 Bashford Drive', 'PO Box 51643', 'Brniště', 'Mont.', '471 29', '751-265-2290', '470', 'https://1+.fps', 'In Progress', 'https://www\.bterfryljk\.com');
insert into Company_LCIAA (id, company_name, Address_1, address_2, City, State, Zip_Code, Phone_Number, SIC_Code, Social_Media_Link, Status, Company_Webpage) values (17, 'Shufflebeat', '631 Cardinal Junction', 'Room 1874', 'Fonte do Feto', 'Fla.', '2835-526', '177-626-6579', '116', 'http://D+.XYd', 'In Progress', 'sqkeadrp\.com');
insert into Company_LCIAA (id, company_name, Address_1, address_2, City, State, Zip_Code, Phone_Number, SIC_Code, Social_Media_Link, Status, Company_Webpage) values (18, 'Yadel', '554 Acker Terrace', '17th Floor', 'Kabīrwāla', 'Mo.', '57301', '220-778-3665', '763', 'http://c+.px/S*', 'Pending', 'www\.prukpwweid\.net');
insert into Company_LCIAA (id, company_name, Address_1, address_2, City, State, Zip_Code, Phone_Number, SIC_Code, Social_Media_Link, Status, Company_Webpage) values (19, 'Riffpath', '0 Mayfield Terrace', 'Room 1108', 'Denton', 'N.J.', '76210', '940-635-8668', '582', 'https://5+.lYI', 'In Progress', 'ryrrrpqwry\.org');
insert into Company_LCIAA (id, company_name, Address_1, address_2, City, State, Zip_Code, Phone_Number, SIC_Code, Social_Media_Link, Status, Company_Webpage) values (20, 'Twinte', '57743 Raven Way', 'Suite 96', 'Slawharad', 'S.D.', null, '996-445-5632', '457', 'http://s+.VLZ/S*', 'In Progress', 'www\.xqsiiiuasr\.com');
insert into Company_LCIAA (id, company_name, Address_1, address_2, City, State, Zip_Code, Phone_Number, SIC_Code, Social_Media_Link, Status, Company_Webpage) values (21, 'Jabbertype', '5 Lakewood Gardens Circle', 'PO Box 93632', 'Šalovci', 'Ark.', '9204', '562-899-8411', '648', 'https://3+.bt/S*', 'In Progress', 'gheyi\.com');
insert into Company_LCIAA (id, company_name, Address_1, address_2, City, State, Zip_Code, Phone_Number, SIC_Code, Social_Media_Link, Status, Company_Webpage) values (22, 'Browseblab', '28671 Moulton Court', '20th Floor', 'Chunhua', 'Utah', null, '598-350-8644', '711', 'http://3+.cN/S*', 'Pending', 'https://www\.wzifcu\.net');
insert into Company_LCIAA (id, company_name, Address_1, address_2, City, State, Zip_Code, Phone_Number, SIC_Code, Social_Media_Link, Status, Company_Webpage) values (23, 'Twinte', '8 Claremont Pass', 'Suite 14', 'Shazi', 'Mass.', null, '371-458-6668', '955', 'http://b+.SmQ', 'Pending', 'cuvwjtgs\.org');
insert into Company_LCIAA (id, company_name, Address_1, address_2, City, State, Zip_Code, Phone_Number, SIC_Code, Social_Media_Link, Status, Company_Webpage) values (24, 'Photospace', '1 Hooker Trail', 'Room 1209', 'Kirkton', 'Mont.', 'KW10', '161-847-5538', '657', 'http://x+.yZL', 'In Progress', 'https://www\.rktzch\.org');
insert into Company_LCIAA (id, company_name, Address_1, address_2, City, State, Zip_Code, Phone_Number, SIC_Code, Social_Media_Link, Status, Company_Webpage) values (25, 'Tanoodle', '06254 Westridge Lane', 'Apt 776', 'Telsen', 'Maine', '9121', '687-616-6121', '664', 'https://Y+.Sq/S*', 'Pending', 'http://www\.xozll\.com');
insert into Company_LCIAA (id, company_name, Address_1, address_2, City, State, Zip_Code, Phone_Number, SIC_Code, Social_Media_Link, Status, Company_Webpage) values (26, 'Mynte', '9560 Welch Pass', 'Apt 944', 'Fuliang', 'Pa.', null, '848-755-2244', '478', 'https://5+.Jq/S*', 'In Progress', 'ewldzhpua\.net');
insert into Company_LCIAA (id, company_name, Address_1, address_2, City, State, Zip_Code, Phone_Number, SIC_Code, Social_Media_Link, Status, Company_Webpage) values (27, 'Kwideo', '876 Charing Cross Plaza', 'Room 960', 'Yumbo', 'Colo.', '760508', '109-368-1802', '503', 'http://1+.aI/S*', 'Pending', 'http://kqsop\.com');
insert into Company_LCIAA (id, company_name, Address_1, address_2, City, State, Zip_Code, Phone_Number, SIC_Code, Social_Media_Link, Status, Company_Webpage) values (28, 'Tagcat', '197 Springview Road', 'Suite 69', 'Wissous', 'Alaska', '91324 CEDEX', '591-243-9720', '752', 'http://r+.lY', 'Pending', 'www\.eqjvj\.com');
insert into Company_LCIAA (id, company_name, Address_1, address_2, City, State, Zip_Code, Phone_Number, SIC_Code, Social_Media_Link, Status, Company_Webpage) values (29, 'Fivespan', '3 Jana Terrace', 'Apt 663', 'Marialva', 'Va.', '86990-000', '432-782-7859', '287', 'https://v+.pf', 'In Progress', 'www\.mjqilxy\.org');
insert into Company_LCIAA (id, company_name, Address_1, address_2, City, State, Zip_Code, Phone_Number, SIC_Code, Social_Media_Link, Status, Company_Webpage) values (30, 'JumpXS', '12 Cambridge Parkway', '18th Floor', 'Bangus Kulon', 'Ind.', null, '581-303-2181', '667', 'http://9+.KRQ/S*', 'Pending', 'http://uatmw\.net');
